theme: jekyll-theme-minimal
title: [COVIDPERU]
logo: blob/f3378bad8006082fdb888443e72f54c3e33c8314/logo.png
description: "The COVIDPERU is project which have goal to analyze COVID´s data set on Peru. Before that whole information have downloaded Peruvian government´s source."
show_downloads: ["true"]
google_analytics: [G-YYYC4TQEDL]
