theme: jekyll-theme-minimal
title: [COVIDPERU]
logo: https://github.com/jasb3110/COVIDPERU/blob/344ece0c5fa6cd264af570fa4f645859f27fa8dd/logo.png
description: "The COVIDPERU is project which have goal to analyze COVID´s data set on Peru. Before that whole information have downloaded Peruvian government´s source."
show_downloads: ["true"]
google_analytics: [G-YYYC4TQEDL]
